[project]
name = "receipt-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "baml-py>=0.70.5",
    "fastapi>=0.115.6",
    "pillow>=11.0.0",
]
